# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 641)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftPanelDashboard = QtWidgets.QFrame(self.centralwidget)
        self.leftPanelDashboard.setMinimumSize(QtCore.QSize(60, 0))
        self.leftPanelDashboard.setStyleSheet("background-color: #DFDFDF; border-radius: 15px;")
        self.leftPanelDashboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanelDashboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftPanelDashboard.setObjectName("leftPanelDashboard")
        self.horizontalLayout_2.addWidget(self.leftPanelDashboard)
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appTitleLabel = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.appTitleLabel.setFont(font)
        self.appTitleLabel.setStyleSheet("color: #343434")
        self.appTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitleLabel.setObjectName("appTitleLabel")
        self.verticalLayout.addWidget(self.appTitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pagesWidget = QtWidgets.QStackedWidget(self.mainFrame)
        self.pagesWidget.setObjectName("pagesWidget")
        self.taskListPage = QtWidgets.QWidget()
        self.taskListPage.setObjectName("taskListPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.taskListPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.taskListScroll = QtWidgets.QScrollArea(self.taskListPage)
        self.taskListScroll.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white;  /* Tło scrollbara */\n"
"    width: 5px;         /* Szerokość scrollbara */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;  /* Kolor uchwytu */\n"
"    border-radius: 5px;   /* Zaokrąglenie uchwytu */\n"
"    min-height: 20px;    /* Minimalna wysokość uchwytu */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;    /* Usunięcie strzałek */\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;    /* Tło obszaru poza uchwytem */\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:none;\n"
"}")
        self.taskListScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.taskListScroll.setWidgetResizable(True)
        self.taskListScroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.taskListScroll.setObjectName("taskListScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 513, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.taskFrameTemplate = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.taskFrameTemplate.setMinimumSize(QtCore.QSize(480, 60))
        self.taskFrameTemplate.setMaximumSize(QtCore.QSize(16777215, 80))
        self.taskFrameTemplate.setStyleSheet("QFrame{\n"
"background-color:#DFDFDF;\n"
"border: none;\n"
"border-radius: 15px;\n"
"color: #343434;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.taskFrameTemplate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.taskFrameTemplate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskFrameTemplate.setObjectName("taskFrameTemplate")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.taskFrameTemplate)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.taskContentLabelTemplate = QtWidgets.QLabel(self.taskFrameTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskContentLabelTemplate.sizePolicy().hasHeightForWidth())
        self.taskContentLabelTemplate.setSizePolicy(sizePolicy)
        self.taskContentLabelTemplate.setMinimumSize(QtCore.QSize(16777215, 20))
        self.taskContentLabelTemplate.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskContentLabelTemplate.setFont(font)
        self.taskContentLabelTemplate.setStyleSheet("border: none;\n"
"color: #343434;\n"
"background-color: none;\n"
"")
        self.taskContentLabelTemplate.setWordWrap(True)
        self.taskContentLabelTemplate.setObjectName("taskContentLabelTemplate")
        self.horizontalLayout_5.addWidget(self.taskContentLabelTemplate)
        self.trashButtonTaskTemplate = QtWidgets.QPushButton(self.taskFrameTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashButtonTaskTemplate.sizePolicy().hasHeightForWidth())
        self.trashButtonTaskTemplate.setSizePolicy(sizePolicy)
        self.trashButtonTaskTemplate.setMinimumSize(QtCore.QSize(40, 40))
        self.trashButtonTaskTemplate.setMaximumSize(QtCore.QSize(50, 50))
        self.trashButtonTaskTemplate.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b3b3b3;\n"
"}")
        self.trashButtonTaskTemplate.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trashButtonTaskTemplate.setIcon(icon)
        self.trashButtonTaskTemplate.setIconSize(QtCore.QSize(17, 16))
        self.trashButtonTaskTemplate.setObjectName("trashButtonTaskTemplate")
        self.horizontalLayout_5.addWidget(self.trashButtonTaskTemplate)
        self.verticalLayout_8.addWidget(self.taskFrameTemplate)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.taskListScroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.taskListScroll)
        self.pagesWidget.addWidget(self.taskListPage)
        self.addTaskPage = QtWidgets.QWidget()
        self.addTaskPage.setAutoFillBackground(False)
        self.addTaskPage.setObjectName("addTaskPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.addTaskPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.taskNameInput = QtWidgets.QLineEdit(self.addTaskPage)
        self.taskNameInput.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.taskNameInput.setFont(font)
        self.taskNameInput.setStyleSheet("border:none;\n"
"background-color: #8170F4;\n"
"color:white;\n"
"border-radius: 15px;\n"
"border-bottom: 1px solid grey;")
        self.taskNameInput.setMaxLength(100)
        self.taskNameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.taskNameInput.setObjectName("taskNameInput")
        self.verticalLayout_2.addWidget(self.taskNameInput)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.addTaskPage)
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.addTaskPage)
        self.frame.setStyleSheet("border: none;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.addNewTaskBtn = QtWidgets.QPushButton(self.frame)
        self.addNewTaskBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addNewTaskBtn.setFont(font)
        self.addNewTaskBtn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"background-color: #8170F4;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #725EF4;\n"
"}\n"
"\n"
"\n"
"")
        self.addNewTaskBtn.setObjectName("addNewTaskBtn")
        self.verticalLayout_10.addWidget(self.addNewTaskBtn)
        self.backToPage1Btn = QtWidgets.QPushButton(self.frame)
        self.backToPage1Btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.backToPage1Btn.setFont(font)
        self.backToPage1Btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"background-color: #8170F4;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #725EF4;\n"
"}\n"
"\n"
"\n"
"")
        self.backToPage1Btn.setObjectName("backToPage1Btn")
        self.verticalLayout_10.addWidget(self.backToPage1Btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.addTaskPage)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.pagesWidget.addWidget(self.addTaskPage)
        self.horizontalLayout.addWidget(self.pagesWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.openAddPageBtn = QtWidgets.QPushButton(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openAddPageBtn.sizePolicy().hasHeightForWidth())
        self.openAddPageBtn.setSizePolicy(sizePolicy)
        self.openAddPageBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.openAddPageBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.openAddPageBtn.setToolTipDuration(-1)
        self.openAddPageBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.openAddPageBtn.setAutoFillBackground(False)
        self.openAddPageBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8170F4;\n"
"    border-radius: 15px;  /* Połowa wymiaru przycisku (30px/2) */\n"
"    border: none;\n"
"    padding: 0;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #725EF4;\n"
"}")
        self.openAddPageBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAddPageBtn.setIcon(icon1)
        self.openAddPageBtn.setIconSize(QtCore.QSize(50, 50))
        self.openAddPageBtn.setObjectName("openAddPageBtn")
        self.verticalLayout_5.addWidget(self.openAddPageBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pagesWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWindowFilePath(_translate("MainWindow", "background-color: #FFFFFF;"))
        self.appTitleLabel.setText(_translate("MainWindow", "TODO LIST"))
        self.taskContentLabelTemplate.setText(_translate("MainWindow", "Lorem ipsum"))
        self.taskNameInput.setPlaceholderText(_translate("MainWindow", "E.g. buy 10 eggs."))
        self.addNewTaskBtn.setText(_translate("MainWindow", "ADD"))
        self.backToPage1Btn.setText(_translate("MainWindow", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
