# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 641)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftPanelDashboard = QtWidgets.QFrame(self.centralwidget)
        self.leftPanelDashboard.setMinimumSize(QtCore.QSize(60, 0))
        self.leftPanelDashboard.setStyleSheet("background-color: #DFDFDF; border-radius: 15px;")
        self.leftPanelDashboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftPanelDashboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftPanelDashboard.setObjectName("leftPanelDashboard")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftPanelDashboard)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeBtn = QtWidgets.QPushButton(self.leftPanelDashboard)
        self.homeBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.homeBtn.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.homeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QtCore.QSize(40, 40))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_3.addWidget(self.homeBtn)
        self.shopBtn = QtWidgets.QPushButton(self.leftPanelDashboard)
        self.shopBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.shopBtn.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.shopBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shopBtn.setIcon(icon1)
        self.shopBtn.setIconSize(QtCore.QSize(40, 40))
        self.shopBtn.setObjectName("shopBtn")
        self.verticalLayout_3.addWidget(self.shopBtn)
        self.schoolBtn = QtWidgets.QPushButton(self.leftPanelDashboard)
        self.schoolBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.schoolBtn.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.schoolBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/graduation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schoolBtn.setIcon(icon2)
        self.schoolBtn.setIconSize(QtCore.QSize(40, 40))
        self.schoolBtn.setObjectName("schoolBtn")
        self.verticalLayout_3.addWidget(self.schoolBtn)
        self.jobBtn = QtWidgets.QPushButton(self.leftPanelDashboard)
        self.jobBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.jobBtn.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.jobBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/briefcase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jobBtn.setIcon(icon3)
        self.jobBtn.setIconSize(QtCore.QSize(40, 40))
        self.jobBtn.setObjectName("jobBtn")
        self.verticalLayout_3.addWidget(self.jobBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.exitBtn = QtWidgets.QPushButton(self.leftPanelDashboard)
        self.exitBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.exitBtn.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.exitBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon4)
        self.exitBtn.setIconSize(QtCore.QSize(40, 40))
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout_3.addWidget(self.exitBtn)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.leftPanelDashboard)
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appTitleLabel = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.appTitleLabel.setFont(font)
        self.appTitleLabel.setStyleSheet("color: #343434")
        self.appTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitleLabel.setObjectName("appTitleLabel")
        self.verticalLayout.addWidget(self.appTitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pagesWidget = QtWidgets.QStackedWidget(self.mainFrame)
        self.pagesWidget.setObjectName("pagesWidget")
        self.taskListPage = QtWidgets.QWidget()
        self.taskListPage.setObjectName("taskListPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.taskListPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.taskListScroll = QtWidgets.QScrollArea(self.taskListPage)
        self.taskListScroll.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white;  /* Tło scrollbara */\n"
"    width: 5px;         /* Szerokość scrollbara */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;  /* Kolor uchwytu */\n"
"    border-radius: 5px;   /* Zaokrąglenie uchwytu */\n"
"    min-height: 20px;    /* Minimalna wysokość uchwytu */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;    /* Usunięcie strzałek */\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;    /* Tło obszaru poza uchwytem */\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:none;\n"
"}")
        self.taskListScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.taskListScroll.setWidgetResizable(True)
        self.taskListScroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.taskListScroll.setObjectName("taskListScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 503, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #343434")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.taskFrameTemplate = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.taskFrameTemplate.setMinimumSize(QtCore.QSize(480, 60))
        self.taskFrameTemplate.setMaximumSize(QtCore.QSize(16777215, 80))
        self.taskFrameTemplate.setStyleSheet("QFrame{\n"
"background-color:#DFDFDF;\n"
"border: none;\n"
"border-radius: 15px;\n"
"color: #343434;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.taskFrameTemplate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.taskFrameTemplate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskFrameTemplate.setObjectName("taskFrameTemplate")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.taskFrameTemplate)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.taskContentLabelTemplate = QtWidgets.QLabel(self.taskFrameTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskContentLabelTemplate.sizePolicy().hasHeightForWidth())
        self.taskContentLabelTemplate.setSizePolicy(sizePolicy)
        self.taskContentLabelTemplate.setMinimumSize(QtCore.QSize(0, 20))
        self.taskContentLabelTemplate.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskContentLabelTemplate.setFont(font)
        self.taskContentLabelTemplate.setStyleSheet("border: none;\n"
"color: #343434;\n"
"background-color: none;\n"
"")
        self.taskContentLabelTemplate.setWordWrap(True)
        self.taskContentLabelTemplate.setObjectName("taskContentLabelTemplate")
        self.horizontalLayout_5.addWidget(self.taskContentLabelTemplate)
        self.trashButtonTaskTemplate = QtWidgets.QPushButton(self.taskFrameTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashButtonTaskTemplate.sizePolicy().hasHeightForWidth())
        self.trashButtonTaskTemplate.setSizePolicy(sizePolicy)
        self.trashButtonTaskTemplate.setMinimumSize(QtCore.QSize(40, 40))
        self.trashButtonTaskTemplate.setMaximumSize(QtCore.QSize(50, 50))
        self.trashButtonTaskTemplate.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b3b3b3;\n"
"}")
        self.trashButtonTaskTemplate.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/recycle-bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trashButtonTaskTemplate.setIcon(icon5)
        self.trashButtonTaskTemplate.setIconSize(QtCore.QSize(17, 16))
        self.trashButtonTaskTemplate.setObjectName("trashButtonTaskTemplate")
        self.horizontalLayout_5.addWidget(self.trashButtonTaskTemplate)
        self.verticalLayout_8.addWidget(self.taskFrameTemplate)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.taskListScroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.taskListScroll)
        self.pagesWidget.addWidget(self.taskListPage)
        self.addTaskPage = QtWidgets.QWidget()
        self.addTaskPage.setAutoFillBackground(False)
        self.addTaskPage.setObjectName("addTaskPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.addTaskPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.taskNameInput = QtWidgets.QLineEdit(self.addTaskPage)
        self.taskNameInput.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.taskNameInput.setFont(font)
        self.taskNameInput.setStyleSheet("border:none;\n"
"background-color: #8170F4;\n"
"color:white;\n"
"border-radius: 15px;\n"
"border-bottom: 1px solid grey;")
        self.taskNameInput.setMaxLength(100)
        self.taskNameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.taskNameInput.setObjectName("taskNameInput")
        self.verticalLayout_2.addWidget(self.taskNameInput)
        self.taskCategorySelect = QtWidgets.QComboBox(self.addTaskPage)
        self.taskCategorySelect.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.taskCategorySelect.setFont(font)
        self.taskCategorySelect.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    background-color: #8170F4;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    padding-left: 10px;\n"
"    padding-right: 25px; /* miejsce na strzałkę */\n"
"    border-bottom: 1px solid grey;\n"
"}\n"
"\n"
"/* Strzałka rozwijania - prosty trójkąt, bez ramki */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none; /* usunięcie domyślnej strzałki */\n"
"    border: none;\n"
"    width: 0; \n"
"    height: 0;\n"
"    border-left: 6px solid transparent;\n"
"    border-right: 6px solid transparent;\n"
"    border-top: 6px solid white; /* biała strzałka w górę */\n"
"    margin-right: 6px;\n"
"}\n"
"")
        self.taskCategorySelect.setObjectName("taskCategorySelect")
        self.taskCategorySelect.addItem("")
        self.taskCategorySelect.addItem("")
        self.taskCategorySelect.addItem("")
        self.taskCategorySelect.addItem("")
        self.taskCategorySelect.addItem("")
        self.verticalLayout_2.addWidget(self.taskCategorySelect)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.addTaskPage)
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.addTaskPage)
        self.frame.setStyleSheet("border: none;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.addNewTaskBtn = QtWidgets.QPushButton(self.frame)
        self.addNewTaskBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addNewTaskBtn.setFont(font)
        self.addNewTaskBtn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"background-color: #8170F4;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #725EF4;\n"
"}\n"
"\n"
"\n"
"")
        self.addNewTaskBtn.setObjectName("addNewTaskBtn")
        self.verticalLayout_10.addWidget(self.addNewTaskBtn)
        self.backToPage1Btn = QtWidgets.QPushButton(self.frame)
        self.backToPage1Btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.backToPage1Btn.setFont(font)
        self.backToPage1Btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"background-color: #8170F4;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #725EF4;\n"
"}\n"
"\n"
"\n"
"")
        self.backToPage1Btn.setObjectName("backToPage1Btn")
        self.verticalLayout_10.addWidget(self.backToPage1Btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.addTaskPage)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.pagesWidget.addWidget(self.addTaskPage)
        self.homeTaskListPage = QtWidgets.QWidget()
        self.homeTaskListPage.setObjectName("homeTaskListPage")
        self.pagesWidget.addWidget(self.homeTaskListPage)
        self.shopTaskListPage = QtWidgets.QWidget()
        self.shopTaskListPage.setObjectName("shopTaskListPage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.shopTaskListPage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.shopTaskListPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #343434")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.shopScrollArea = QtWidgets.QScrollArea(self.shopTaskListPage)
        self.shopScrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white;  /* Tło scrollbara */\n"
"    width: 5px;         /* Szerokość scrollbara */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;  /* Kolor uchwytu */\n"
"    border-radius: 5px;   /* Zaokrąglenie uchwytu */\n"
"    min-height: 20px;    /* Minimalna wysokość uchwytu */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;    /* Usunięcie strzałek */\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;    /* Tło obszaru poza uchwytem */\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:none;\n"
"}\n"
"")
        self.shopScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.shopScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shopScrollArea.setWidgetResizable(True)
        self.shopScrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.shopScrollArea.setObjectName("shopScrollArea")
        self.shopScrollAreaWidgetContents = QtWidgets.QWidget()
        self.shopScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 503, 462))
        self.shopScrollAreaWidgetContents.setObjectName("shopScrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.shopScrollAreaWidgetContents)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.taskFrameTemplate_2 = QtWidgets.QFrame(self.shopScrollAreaWidgetContents)
        self.taskFrameTemplate_2.setMinimumSize(QtCore.QSize(480, 60))
        self.taskFrameTemplate_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.taskFrameTemplate_2.setStyleSheet("QFrame{\n"
"background-color:#DFDFDF;\n"
"border: none;\n"
"border-radius: 15px;\n"
"color: #343434;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.taskFrameTemplate_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.taskFrameTemplate_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskFrameTemplate_2.setObjectName("taskFrameTemplate_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.taskFrameTemplate_2)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.taskContentLabelTemplate_2 = QtWidgets.QLabel(self.taskFrameTemplate_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskContentLabelTemplate_2.sizePolicy().hasHeightForWidth())
        self.taskContentLabelTemplate_2.setSizePolicy(sizePolicy)
        self.taskContentLabelTemplate_2.setMinimumSize(QtCore.QSize(0, 20))
        self.taskContentLabelTemplate_2.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskContentLabelTemplate_2.setFont(font)
        self.taskContentLabelTemplate_2.setStyleSheet("border: none;\n"
"color: #343434;\n"
"background-color: none;\n"
"")
        self.taskContentLabelTemplate_2.setWordWrap(True)
        self.taskContentLabelTemplate_2.setObjectName("taskContentLabelTemplate_2")
        self.horizontalLayout_6.addWidget(self.taskContentLabelTemplate_2)
        self.trashButtonTaskTemplate_2 = QtWidgets.QPushButton(self.taskFrameTemplate_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashButtonTaskTemplate_2.sizePolicy().hasHeightForWidth())
        self.trashButtonTaskTemplate_2.setSizePolicy(sizePolicy)
        self.trashButtonTaskTemplate_2.setMinimumSize(QtCore.QSize(40, 40))
        self.trashButtonTaskTemplate_2.setMaximumSize(QtCore.QSize(50, 50))
        self.trashButtonTaskTemplate_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b3b3b3;\n"
"}")
        self.trashButtonTaskTemplate_2.setText("")
        self.trashButtonTaskTemplate_2.setIcon(icon5)
        self.trashButtonTaskTemplate_2.setIconSize(QtCore.QSize(17, 16))
        self.trashButtonTaskTemplate_2.setObjectName("trashButtonTaskTemplate_2")
        self.horizontalLayout_6.addWidget(self.trashButtonTaskTemplate_2)
        self.verticalLayout_13.addWidget(self.taskFrameTemplate_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem5)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.shopScrollArea.setWidget(self.shopScrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.shopScrollArea)
        self.pagesWidget.addWidget(self.shopTaskListPage)
        self.schoolTaskListPage = QtWidgets.QWidget()
        self.schoolTaskListPage.setObjectName("schoolTaskListPage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.schoolTaskListPage)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label = QtWidgets.QLabel(self.schoolTaskListPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #343434")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.schoolScrollArea = QtWidgets.QScrollArea(self.schoolTaskListPage)
        self.schoolScrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white;  /* Tło scrollbara */\n"
"    width: 5px;         /* Szerokość scrollbara */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;  /* Kolor uchwytu */\n"
"    border-radius: 5px;   /* Zaokrąglenie uchwytu */\n"
"    min-height: 20px;    /* Minimalna wysokość uchwytu */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;    /* Usunięcie strzałek */\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;    /* Tło obszaru poza uchwytem */\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:none;\n"
"}\n"
"")
        self.schoolScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.schoolScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.schoolScrollArea.setWidgetResizable(True)
        self.schoolScrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.schoolScrollArea.setObjectName("schoolScrollArea")
        self.schoolScrollAreaWidgetContents = QtWidgets.QWidget()
        self.schoolScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 503, 462))
        self.schoolScrollAreaWidgetContents.setObjectName("schoolScrollAreaWidgetContents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.schoolScrollAreaWidgetContents)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.taskFrameTemplate_3 = QtWidgets.QFrame(self.schoolScrollAreaWidgetContents)
        self.taskFrameTemplate_3.setMinimumSize(QtCore.QSize(480, 60))
        self.taskFrameTemplate_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.taskFrameTemplate_3.setStyleSheet("QFrame{\n"
"background-color:#DFDFDF;\n"
"border: none;\n"
"border-radius: 15px;\n"
"color: #343434;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.taskFrameTemplate_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.taskFrameTemplate_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskFrameTemplate_3.setObjectName("taskFrameTemplate_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.taskFrameTemplate_3)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.taskContentLabelTemplate_3 = QtWidgets.QLabel(self.taskFrameTemplate_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskContentLabelTemplate_3.sizePolicy().hasHeightForWidth())
        self.taskContentLabelTemplate_3.setSizePolicy(sizePolicy)
        self.taskContentLabelTemplate_3.setMinimumSize(QtCore.QSize(0, 20))
        self.taskContentLabelTemplate_3.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskContentLabelTemplate_3.setFont(font)
        self.taskContentLabelTemplate_3.setStyleSheet("border: none;\n"
"color: #343434;\n"
"background-color: none;\n"
"")
        self.taskContentLabelTemplate_3.setWordWrap(True)
        self.taskContentLabelTemplate_3.setObjectName("taskContentLabelTemplate_3")
        self.horizontalLayout_7.addWidget(self.taskContentLabelTemplate_3)
        self.trashButtonTaskTemplate_3 = QtWidgets.QPushButton(self.taskFrameTemplate_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashButtonTaskTemplate_3.sizePolicy().hasHeightForWidth())
        self.trashButtonTaskTemplate_3.setSizePolicy(sizePolicy)
        self.trashButtonTaskTemplate_3.setMinimumSize(QtCore.QSize(40, 40))
        self.trashButtonTaskTemplate_3.setMaximumSize(QtCore.QSize(50, 50))
        self.trashButtonTaskTemplate_3.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b3b3b3;\n"
"}")
        self.trashButtonTaskTemplate_3.setText("")
        self.trashButtonTaskTemplate_3.setIcon(icon5)
        self.trashButtonTaskTemplate_3.setIconSize(QtCore.QSize(17, 16))
        self.trashButtonTaskTemplate_3.setObjectName("trashButtonTaskTemplate_3")
        self.horizontalLayout_7.addWidget(self.trashButtonTaskTemplate_3)
        self.verticalLayout_15.addWidget(self.taskFrameTemplate_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem6)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.schoolScrollArea.setWidget(self.schoolScrollAreaWidgetContents)
        self.verticalLayout_16.addWidget(self.schoolScrollArea)
        self.pagesWidget.addWidget(self.schoolTaskListPage)
        self.jobTaskListPage = QtWidgets.QWidget()
        self.jobTaskListPage.setObjectName("jobTaskListPage")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.jobTaskListPage)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.jobTaskListPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #343434")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_19.addWidget(self.label_2)
        self.jobScrollArea = QtWidgets.QScrollArea(self.jobTaskListPage)
        self.jobScrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white;  /* Tło scrollbara */\n"
"    width: 5px;         /* Szerokość scrollbara */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;  /* Kolor uchwytu */\n"
"    border-radius: 5px;   /* Zaokrąglenie uchwytu */\n"
"    min-height: 20px;    /* Minimalna wysokość uchwytu */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;    /* Usunięcie strzałek */\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;    /* Tło obszaru poza uchwytem */\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:none;\n"
"}\n"
"")
        self.jobScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.jobScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.jobScrollArea.setWidgetResizable(True)
        self.jobScrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.jobScrollArea.setObjectName("jobScrollArea")
        self.jobScrollAreaWidgetContents = QtWidgets.QWidget()
        self.jobScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 503, 462))
        self.jobScrollAreaWidgetContents.setObjectName("jobScrollAreaWidgetContents")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.jobScrollAreaWidgetContents)
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.taskFrameTemplate_4 = QtWidgets.QFrame(self.jobScrollAreaWidgetContents)
        self.taskFrameTemplate_4.setMinimumSize(QtCore.QSize(480, 60))
        self.taskFrameTemplate_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.taskFrameTemplate_4.setStyleSheet("QFrame{\n"
"background-color:#DFDFDF;\n"
"border: none;\n"
"border-radius: 15px;\n"
"color: #343434;\n"
"\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #cccccc;\n"
"}")
        self.taskFrameTemplate_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.taskFrameTemplate_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskFrameTemplate_4.setObjectName("taskFrameTemplate_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.taskFrameTemplate_4)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.taskContentLabelTemplate_4 = QtWidgets.QLabel(self.taskFrameTemplate_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskContentLabelTemplate_4.sizePolicy().hasHeightForWidth())
        self.taskContentLabelTemplate_4.setSizePolicy(sizePolicy)
        self.taskContentLabelTemplate_4.setMinimumSize(QtCore.QSize(0, 20))
        self.taskContentLabelTemplate_4.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskContentLabelTemplate_4.setFont(font)
        self.taskContentLabelTemplate_4.setStyleSheet("border: none;\n"
"color: #343434;\n"
"background-color: none;\n"
"")
        self.taskContentLabelTemplate_4.setWordWrap(True)
        self.taskContentLabelTemplate_4.setObjectName("taskContentLabelTemplate_4")
        self.horizontalLayout_8.addWidget(self.taskContentLabelTemplate_4)
        self.trashButtonTaskTemplate_4 = QtWidgets.QPushButton(self.taskFrameTemplate_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trashButtonTaskTemplate_4.sizePolicy().hasHeightForWidth())
        self.trashButtonTaskTemplate_4.setSizePolicy(sizePolicy)
        self.trashButtonTaskTemplate_4.setMinimumSize(QtCore.QSize(40, 40))
        self.trashButtonTaskTemplate_4.setMaximumSize(QtCore.QSize(50, 50))
        self.trashButtonTaskTemplate_4.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b3b3b3;\n"
"}")
        self.trashButtonTaskTemplate_4.setText("")
        self.trashButtonTaskTemplate_4.setIcon(icon5)
        self.trashButtonTaskTemplate_4.setIconSize(QtCore.QSize(17, 16))
        self.trashButtonTaskTemplate_4.setObjectName("trashButtonTaskTemplate_4")
        self.horizontalLayout_8.addWidget(self.trashButtonTaskTemplate_4)
        self.verticalLayout_18.addWidget(self.taskFrameTemplate_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem7)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.jobScrollArea.setWidget(self.jobScrollAreaWidgetContents)
        self.verticalLayout_19.addWidget(self.jobScrollArea)
        self.pagesWidget.addWidget(self.jobTaskListPage)
        self.horizontalLayout.addWidget(self.pagesWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.openAddPageBtn = QtWidgets.QPushButton(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openAddPageBtn.sizePolicy().hasHeightForWidth())
        self.openAddPageBtn.setSizePolicy(sizePolicy)
        self.openAddPageBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.openAddPageBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.openAddPageBtn.setToolTipDuration(-1)
        self.openAddPageBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.openAddPageBtn.setAutoFillBackground(False)
        self.openAddPageBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8170F4;\n"
"    border-radius: 15px;  /* Połowa wymiaru przycisku (30px/2) */\n"
"    border: none;\n"
"    padding: 0;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #725EF4;\n"
"}")
        self.openAddPageBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAddPageBtn.setIcon(icon6)
        self.openAddPageBtn.setIconSize(QtCore.QSize(50, 50))
        self.openAddPageBtn.setObjectName("openAddPageBtn")
        self.verticalLayout_5.addWidget(self.openAddPageBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pagesWidget.setCurrentIndex(5)
        self.taskCategorySelect.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWindowFilePath(_translate("MainWindow", "background-color: #FFFFFF;"))
        self.appTitleLabel.setText(_translate("MainWindow", "TO DO LIST"))
        self.label_3.setText(_translate("MainWindow", "All tasks"))
        self.taskContentLabelTemplate.setText(_translate("MainWindow", "Lorem ipsum"))
        self.taskNameInput.setPlaceholderText(_translate("MainWindow", "E.g. buy 10 eggs."))
        self.taskCategorySelect.setCurrentText(_translate("MainWindow", "Select category"))
        self.taskCategorySelect.setItemText(0, _translate("MainWindow", "Select category"))
        self.taskCategorySelect.setItemText(1, _translate("MainWindow", "General"))
        self.taskCategorySelect.setItemText(2, _translate("MainWindow", "Shopping list"))
        self.taskCategorySelect.setItemText(3, _translate("MainWindow", "School list"))
        self.taskCategorySelect.setItemText(4, _translate("MainWindow", "Job list"))
        self.addNewTaskBtn.setText(_translate("MainWindow", "ADD"))
        self.backToPage1Btn.setText(_translate("MainWindow", "BACK"))
        self.label_4.setText(_translate("MainWindow", "Shopping list"))
        self.taskContentLabelTemplate_2.setText(_translate("MainWindow", "Lorem ipsum"))
        self.label.setText(_translate("MainWindow", "School list"))
        self.taskContentLabelTemplate_3.setText(_translate("MainWindow", "Lorem ipsum"))
        self.label_2.setText(_translate("MainWindow", "Job list"))
        self.taskContentLabelTemplate_4.setText(_translate("MainWindow", "Lorem ipsum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
